# jwt 生成密钥
jwt:
  secret: '5ac787d6ded95720ce363852ea970c682758802662f4dda5597a0dc53ca949d9'

# 数据库连接配置
db:
  # 业务数据库配置
  app_1:
    host: '127.0.0.1'
    username: 'root'
    password: '123456'
    database: 'gnews'
    timezone: '+00:00'
    synchronize: false

  # 视频数据库配置
  video:
    host: '127.0.0.1'
    username: 'root'
    password: '123456'
    database: 'telemaster'
    timezone: '+00:00'
    synchronize: false

  # 后台数据库配置
  admin:
    host: '127.0.0.1'
    username: 'root'
    password: '123456'
    database: 'gnews_admin'
    timezone: '+00:00'
    synchronize: true

# Redis 连接配置
redis:
  host: 'localhost'
  port: 6379
  username: ''
  password: ''

# Typesense 连接配置
typesense:
  host: 'localhost'
  port: 8108
  protocol: 'http'
  apiKey: '123456'